title:        Carlos Menezes
tagline:      'Carlos Blog'
description:  'Desenvolvedor web buscando novas tecnologias.
url:          http://andhyde.com
version:      0.0.1
author:
  name:       'carlos'
  email:      'carlosalbertogmenezes@gmail.com'
markdown:     rdiscount
permalink:    pretty
pygments:     true
paginate:     5

encoding: UTF-8
