title:        Carlos Menezes
tagline:      'Carlos Menezes'
year:         2020
description:  'A developer looking for new technologies.'
url:          http://cgmenezes.github.io/
version:      0.0.4
author:
  name:       'Carlos Menezes'
  email:      'carlosalbertogmenezes@gmail.com'
markdown:     rdiscount
permalink:    pretty
pygments:     true
paginate:     5

encoding: UTF-8
