title:        Carlos Menezes
tagline:      'Carlos Blog'
description:  'Web developer searching new technologies.'
url:          http://carlosalbertogmenezes.github.io/
version:      0.0.1
author:
  name:       ''
  email:      ''
markdown:     rdiscount
permalink:    pretty
pygments:     true
paginate:     5

encoding: UTF-8
