title:        Carlos Menezes
tagline:      'Carlos Menezes'
description:  'A developer looking for new technologies.'
url:          http://carlosalbertogmenezes.github.io/
version:      0.0.2
author:
  name:       'carlosalbertogmenezes'
  email:      'carlosalbertogmenezes@gmail.com'
markdown:     rdiscount
permalink:    pretty
pygments:     true
paginate:     5

encoding: UTF-8
